---
dependency:
  name: galaxy
driver:
  name: vagrant
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: instance
    box: ubuntu/bionic64
    # box: ubuntu/focal64
    memory: 2048
    cpus: 2
    config_options:
      ssh.keep_alive: yes
      ssh.remote_user: "vagrant"
      synced_folder: true
      cachier: true
    #interfaces:
    #  # `network_name` is the required identifier, all other keys map to
    #  # arguments.
    #  - network_name: forwarded_port
    #    guest: 19132
    #    host: 19132

provisioner:
  name: ansible
  options:
    vvv: True
  playbooks:
    converge: ../resources/converge.yml
    #create: ../resources/create.yml
    #destroy: ../resources/destroy.yml
verifier:
  name: testinfra
  additional_files_or_dirs:
    - ../../resources/tests/*.py
