---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu
    image: docker.io/pycontribs/ubuntu
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: testinfra
  # directory: ../resources/tests/
  additional_files_or_dirs:
    - ../../resources/tests/*
# resources/tests/test_default.py
# default/molecule.yml
